### ISSUE TITLE
Project description on PyPI is blank

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/adventurelib#13]
[The adventurelib project description on the new PyPI](https://pypi.org/project/adventurelib/) is currently showing up simply as "UNKNOWN".

Additionally, it does not offer a link to this repository - where this is given, pypi.org can show Github stars etc.

**Comment by kajukenbo** [comment]
FWIW, this is still the case.  "Last released: Feb 13, 2018"

**Comment by KeyWeeUsr** [comment]
Should be closed after #26. :)
