### ISSUE TITLE
available in pip2 while not compatible with python 2

### ISSUE THREAD

**Issue by bdavs** [lordmauve/adventurelib#14]
I was able to download the package through pip2 without it throwing an error until I tried running it when I realized it was only for python 3.

**Comment by bdavs** [comment]
Actually I made it compatible with python 2.7 if that would be helpful

**Comment by lordmauve** [comment]
@bdavs You're right that it's an issue that it is happy installing for Python 2 even though it is not Python 2 compatible.

Regarding actually supporting Python 2.7, teachers have told me that they only want to support one version of Python (and obviously that needs to be Python 3). If you think of sharing games written with adventurelib, there's a much better chance of other people's games working when you try to run them if they're all written for Python 3, so I'd rather require that (and incentivise people to use Python 3) than to introduce these potential issues.

**Comment by lordmauve** [comment]
Fixed in 2b00834e960cea01f97578f206ffb4f520cfb091 and released as 1.2.1.
