### ISSUE TITLE
Add a system to limit commands to a specific context

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/adventurelib#2]
Some commands should only be available in a certain context. This would avoid needing to write many `if` checks at the start of each handler.

An API might be

    adventurelib.set_context('limbo')

plus

    @when('give ITEM', context='limbo')

One could also imagine more sophisticated ways of matching contexts - eg. hierarchical:

    adventurelib.set_context('conversation.jerry')

plus

    @when('ask about COLOUR shell', context='conversation')
    def ask_shell(colour):
        say("I don't know about that")

    @when('ask about red shell', context='conversation.samantha')
    def ask_shell(colour):
        say("I have one of those too!")

**Comment by adrianogil** [comment]
I've just submitted a pull-request (#10). If you could take a look, I appreciate any feedback.
