### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sydneyweiss** [lordmauve/adventurelib#7]
We noticed an error on your adventurelib foundation page. Under bags of items, there is this take command: 
@when('take ITEM')
def take(item):
    obj = current_room.take(item)
    if not obj:
        print('There is no %s here.' % item)
    else:
        inventory.add(item)
        print('You take the %s.' % obj)
Instead of obj = current_room.take(item), it should be obj = current_room.items.take(item).
We hope you take this into consideration.
Thank you.

**Comment by olivialongsworth** [comment]
wow this is super cool thanks

**Comment by lordmauve** [comment]
I think this was fixed in #5, but is not yet released.

**Comment by sydneyweiss** [comment]
Wow Thanks a bunch!

**Comment by olivialongsworth** [comment]
@lordmauve @sydneyweiss thx g
